- name: fix searchdomain blah!
  lineinfile: dest=/etc/resolv.conf state=absent regexp="^search (.*)"
  
- name: enable yum cache
  lineinfile: dest=/etc/yum.conf regexp='^(.*)keepcache=(.*)' line='keepcache=1'
  
- name: install packstack repo
  yum: name=https://repos.fedorapeople.org/repos/openstack/openstack-mitaka/rdo-release-mitaka-5.noarch.rpm state=present

- name: installing repo (CentOS)
  yum: name=centos-release-openstack-mitaka state=present
  when: ansible_distribution ==  'CentOS' and ansible_distribution_major_version == '7'

- name: disabling NetworkManager
  service: name=NetworkManager enabled=no state=stopped
  notify:
    - restart Networking

- name: installing packstack
  yum: name=openstack-packstack state=present

- name: answerfile
  template: src=answers.txt.j2 dest=/root/answers.txt
  notify: 
  - installing openstack

