- name: fix searchdomain blah!
  lineinfile: dest=/etc/resolv.conf state=absent regexp="^search (.*)"
  
- name: enable yum cache
  lineinfile: dest=/etc/yum.conf regexp='^(.*)keepcache=(.*)' line='keepcache=1'
  
- name: install packstack repo
  yum: name=https://repos.fedorapeople.org/repos/openstack/openstack-{{ OS_RELEASE }}/rdo-release-{{ OS_RELEASE }}-{{ OS_REVISION }}.noarch.rpm state=present

- name: installing repo (CentOS)
  yum: name=centos-release-openstack-{{ OS_RELEASE }} state=present
  when: ansible_distribution ==  'CentOS' and ansible_distribution_major_version == '7'

- name: disabling NetworkManager
  service: name=NetworkManager enabled=no state=stopped

- name: restart_networking
  service: name=network state=restarted

- name: installing packstack
  yum: name=openstack-packstack state=present

- name: answerfile
  template: src=answers.txt.j2 dest=/root/answers.txt
  notify: 
  - installing openstack

