- name: install packstack repo
  yum: name=https://rdoproject.org/repos/rdo-release.rpm state=present

- name: installing repo (CentOS)
  yum: name=centos-release-openstack-mitaka state=present
  when: ansible_distribution ==  'CentOS' and ansible_distribution_major_version == '7'

- name: disabling NetworkManager
  service: name=NetworkManager enabled=no state=stopped

- name: restart Networking
  service: name=network state=restarted

- name: installing packstack
  yum: name=openstack-packstack state=present

- name: answerfile
  template: src=answers.txt.j2 dest=/root/answers.txt

- name: installing openstack
  command: packstack --answer-file /root/answers.txt