---
# - hosts: openstack
#   become: yes
#   roles:
#     - packstack

# #Patches on openstack install
# - hosts: openstack
#   become: yes
#   tasks:
#     - name: fixing nova api blah
#       lineinfile: dest=/etc/nova/nova.conf regexp='^(.*)api_servers=(.*)' line='api_servers=http://192.168.4.2:9292'
#       notify:
#         - restart nova-compute
#         - restart nova-api
#     - name: fixing nova vnc blah
#       lineinfile: dest=/etc/nova/nova.conf regexp='^(.*)vncserver_proxyclient_address=(.*)' line='vncserver_proxyclient_address=192.168.4.2'
#       notify:
#         - restart nova-compute
#         - restart nova-api
#   handlers: 
#     - name: restart nova-compute
#       service: name=openstack-nova-compute.service state=restarted
#     - name: restart nova-api
#       service: name=openstack-nova-api.service state=restarted

# # #weird errors galore for mitaka
# - hosts: openstack
#   become: yes
#   tasks:
#     - service: name={{ item }} state=restarted
#       with_items:
#         - neutron-server
#         - openstack-nova-api.service
#         - openstack-nova-compute
#       when: OS_RELEASE == "mitaka"

- hosts: openstack
  become: yes
  environment:
    OS_REGION_NAMER: RegionOne
    OS_PASSWORD: '{{ CONFIG_KEYSTONE_ADMIN_PW }}'
    OS_AUTH_URL: http://{{ second_nic_ip }}:5000/v2.0
    OS_USERNAME: admin
    OS_TENANT_NAME: admin
  vars:
    auth_dict:
      password: '{{ CONFIG_KEYSTONE_ADMIN_PW }}'
      auth_url: http://{{ second_nic_ip }}:5000/v2.0
      username: admin
    #WORKAROUND: https://github.com/ansible/ansible-modules-core/issues/4520
  roles:
    - week4

