#otherwise ansible cant do shit
- name: install pip
  yum: name=python-pip state=present
- name: install shade
  pip: name=shade state=present

- include: project.yaml
- include: secgroup.yaml
- include: image.yaml
- include: network.yaml


 
