- name: install pip
  yum: name=python-pip state=present
- name: install shade
  pip: name=shade state=present


- name: create os project
  os_project:
    state: present
    name: "{{ PERSONAL_USER }}project"
    domain: Default
    description: "{{ PERSONAL_USER }}descript"
    enabled: True
- name: create os user
  #command: openstack user create mans --password mans --project mansproject --enable
  os_user:
    auth: '{{ auth_dict }}'
    state: present
    name: "{{ PERSONAL_USER }}"
    password: "{{ PERSONAL_USER }}"
    default_project: "{{ PERSONAL_USER }}project"
- name: downloading cirros image
  get_url: 
    url: http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img
    dest: /root/cirros.img
- name: uploading cirros image
  os_image:
    auth:
      project_name: "{{ PERSONAL_USER }}project"
      auth_url: http://192.168.4.2:5000/v2.0
      username: '{{ PERSONAL_USER }}'
      password: '{{ PERSONAL_USER }}'
    name: cirros
    container_format: bare
    disk_format: qcow2
    state: present
    filename: /root/cirros.img

 - name: creating internalnetwork
   os_network:
    state: present
    project: '{{ PERSONAL_USER }}project'
    name: '{{ PERSONAL_USER }}_intnetwork'
    external: false

 - name: creating internal subnet
   os_subnet:
    state: present
    network_name: '{{ PERSONAL_USER }}_intnetwork'
    name: '{{ PERSONAL_USER }}_intsubnet'
    cidr: 192.168.0.0/24
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8
    allocation_pool_start: 192.168.0.25
    allocation_pool_end: 192.168.0.99

 - name: creating external network
   os_network:
    state: present
    project: '{{ PERSONAL_USER }}project'
    name: '{{ PERSONAL_USER }}_extnetwork'
    external: true

 - name: creating external subnet
   os_subnet:
    state: present
    network_name: '{{ PERSONAL_USER }}_extnetwork'
    name: '{{ PERSONAL_USER }}_extsubnet'
    cidr: 192.168.4.0/24
    enable_dhcp: false
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8
    host_routes:
     - destination: 0.0.0.0/0
       nexthop: 10.0.2.2
     - destination: 192.168.4.0/24
       nexthop: 192.168.4.2
