- name: install pip
  yum: name=python-pip state=present
- name: install shade
  pip: name=shade state=present


- name: create os project
  os_project:
    state: present
    name: "{{ PERSONAL_USER }}project"
    domain: Default
    description: "{{ PERSONAL_USER }}descript"
    enabled: True
- name: create os user
  #command: openstack user create mans --password mans --project mansproject --enable
  os_user:
    auth: '{{ auth_dict }}'
    state: present
    name: "{{ PERSONAL_USER }}"
    password: "{{ PERSONAL_USER }}"
    default_project: "{{ PERSONAL_USER }}project"
